version: '3.3'
services:
  tomcat1:
    image: 18.217.122.146/fda-org/fda-repo:tomcat1
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - 8084:8080
  mysql1:
    image: 18.217.122.146/fda-org/fda-repo:mysql1
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  overlay2:
